spring:
  application:
    name: douyu-live-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:douyu-db-sharding.yaml
    hikari:
      pool-name: douyu-user-pool
      minimum-idle: 150
      maximum-pool-size: 300
      connection-timeout: 4000
      max-lifetime: 60000
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      lettuce:
        pool:
          min-idle: 10
          max-idle: 100
          max-active: 50
douyu:
  rmq:
    producer:
      nameSrv: 127.0.0.1:9876
      groupName: ${spring.application.name}
      retryTimes: 3
      sendTimeOut: 3000
    consumer:
      nameSrv: 127.0.0.1:9876
      groupName: ${spring.application.name}
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://127.0.0.1:8848?namespace=douyu-live-test&&username=nacos&&password=nacos
  protocol:
    name: dubbo
    port: 9091